### ISSUE TITLE
Style 가이드 건의

### ISSUE THREAD

**Issue by ooketmon** [ForUs-KW/NaviForYou_Frontend#8]
styles 하위로 textStyles.js 와 viewStyles를 정리해주신 것을 확인했습니다. 
다만 어떤 경우에 어떤 스타일을 써야하는지 정해지지 않아 사용하기가 어렵네요.. 

당장 급한 사항은 아니지만, 뷰 작업이 끝나고 디자인 입히면서 이에 대한 공통적인 가이드를 만들면 좋을 것 같다는 생각입니다! 
어떻게 생각하시나요 ?
@mi-iron @Bangdayeon

**Comment by Bangdayeon** [comment]
동의합니다.
처음에는 원래 styles.js 하나의 파일로만 만들다가 중간에 두개로라도 나누었는데 뷰 작업이 어느정도 끝나고나면 가이드를 만들면서 나누는 게 좋을 것 같습니다
